/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CustomCard: typeof import('./src/components/CustomCard.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DialogCard: typeof import('./src/components/DialogCard.vue')['default']
    DynamicDialog: typeof import('primevue/dynamicdialog')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Image: typeof import('primevue/image')['default']
    MainFooter: typeof import('./src/components/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SockDialog: typeof import('./src/components/SockDialog.vue')['default']
    SockImageButton: typeof import('./src/components/SockImageButton.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
